# Generated by Django 5.1.3 on 2024-11-28 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название привычки"),
                ),
                (
                    "place",
                    models.CharField(max_length=50, verbose_name="место выполнения"),
                ),
                (
                    "start_time",
                    models.TimeField(verbose_name="время начала выполнения"),
                ),
                (
                    "is_enjoy",
                    models.BooleanField(
                        default=False, verbose_name="приятная привычка"
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(7),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="периодичность (дни)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(max_length=50, verbose_name="вознаграждение"),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=120,
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="время выполнения (с)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="публичная привычка"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to="main.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
        ),
    ]
