# Generated by Django 5.1.3 on 2024-11-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ("name",),
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
