# Generated by Django 5.1.3 on 2024-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="вознаграждение"
            ),
        ),
    ]
