# Generated by Django 5.1.3 on 2024-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_habit_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="send_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="время следующей отправки сообщения в Телеграм",
            ),
        ),
    ]
